name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: example-application

      - name: Install sonar-scanner
        uses: SonarSource/sonarcloud-github-c-cpp@v1

      - name: Initialize
        working-directory: example-application
        run: |
          west init -l .
          west update

      - name: Build firmware
        working-directory: example-application
        run: |
          west build -b custom_plank app

      - name: Twister Tests
        working-directory: example-application
        run: |
          ../zephyr/scripts/twister \
            --ninja \
            --board-root boards/ \
            --platform native_posix \
            --coverage \
            --coverage-tool gcovr \
            --coverage-formats sonarqube \
            --testsuite-root ./tests/

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          sonar-scanner \
            -X \
            --define project.settings=manifest/sonar-project.properties

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: example-application/build/zephyr/zephyr.*
